version: '3'

includes:
  api: ./api/Taskfile.yml
  etcd: ./etcd/Taskfile.yml
  apiserver: ./apiserver/Taskfile.yml
  scheduler: ./scheduler/Taskfile.yml
  kubelet: ./kubelet/Taskfile.yml
  cri: ./cri/Taskfile.yml
  cni: ./cni/Taskfile.yml
  kube-proxy: ./kube-proxy/Taskfile.yml
  controller-manager: ./controller-manager/Taskfile.yml
  toyctl: ./cmd/toyctl/Taskfile.yml
  node: ./node/Taskfile.yml
  images: ./images/Taskfile.yml

tasks:
  build:
    desc: Build every component
    cmds:
      - task: api:build
      - task: etcd:build
      - task: apiserver:build
      - task: scheduler:build
      - task: controller-manager:build
      - task: kubelet:build
      - task: cri:build
      - task: cni:build
      - task: kube-proxy:build
      - task: toyctl:build
      - task: node:build

  test:
    desc: Run every component test
    cmds:
      - task: api:test
      - task: etcd:test
      - task: apiserver:test
      - task: scheduler:test
      - task: kubelet:test
      - task: cri:test
      - task: cni:test
      - task: kube-proxy:test
      - task: controller-manager:test
      - task: toyctl:test
      - task: node:test

  check:
    desc: Check every component environment
    cmds:
      - task: api:check
      - task: etcd:check
      - task: apiserver:check
      - task: scheduler:check
      - task: kubelet:check
      - task: cri:check
      - task: cni:check
      - task: kube-proxy:check
      - task: controller-manager:check
      - task: toyctl:check
      - task: node:check

  run:
    desc: Start virtual nodes and their supervisors
    cmds:
      - task: cri:runtime:build
      - task: apiserver:build
      - task: scheduler:build
      - task: controller-manager:build
      - task: images:prepare-bundle
      - task: kubelet:build
      - task: kube-proxy:build
      - task: node:build
      - sh ./node/scripts/run.sh {{.CLI_ARGS}}
