version: '3'

tasks:
  build:
    silent: true
    cmds:
      - mkdir -p .toy/bin
      - go build -o .toy/bin/kubelet ./cmd/kubelet

  test:
    silent: true
    cmds:
      - go test ./kubelet

  check:
    silent: true
    cmds:
      - task: check:tools
      - task: check:user-namespace
      - task: check:pid-namespace

  check:tools:
    silent: true
    cmds:
      - "command -v go >/dev/null 2>&1 && echo '[kubelet] Go ok' || { echo '[kubelet] Go failed'; exit 1; }"
      - "command -v unshare >/dev/null 2>&1 && echo '[kubelet] unshare ok' || { echo '[kubelet] unshare failed'; exit 1; }"
      - "command -v mount >/dev/null 2>&1 && echo '[kubelet] mount ok' || { echo '[kubelet] mount failed'; exit 1; }"

  check:user-namespace:
    silent: true
    cmds:
      - "unshare --user --map-root-user --fork true >/dev/null 2>&1 && echo '[kubelet] user namespace ok' || { echo '[kubelet] user namespace failed'; exit 1; }"

  check:pid-namespace:
    silent: true
    cmds:
      - "unshare --user --map-root-user --pid --fork true >/dev/null 2>&1 && echo '[kubelet] PID namespace ok' || { echo '[kubelet] PID namespace failed'; exit 1; }"
