version: '3'

tasks:
  build:
    silent: true
    cmds:
      - mkdir -p .toy/bin
      - go build -o .toy/bin/kube-controller-manager ./cmd/controller-manager

  test:
    silent: true
    cmds:
      - go test ./controller-manager

  check:
    silent: true
    cmds:
      - "command -v go >/dev/null 2>&1 && echo '[controller-manager] Go ok' || { echo '[controller-manager] Go failed'; exit 1; }"
