apiVersion: v1
kind: Pod
metadata:
  name: etcd
spec:
  hostNetwork: true
  containers:
    - name: etcd
      image: etcd
      command:
        - /toy/bin/etcd
        - --data-dir
        - /var/lib/etcd
