apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: kube-scheduler
      command:
        - /toy/bin/kube-scheduler
        - -api-server
        - http://127.0.0.1:8080
