apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
spec:
  hostNetwork: true
  containers:
    - name: kube-apiserver
      image: kube-apiserver
      command:
        - /toy/bin/kube-apiserver
        - -listen
        - 0.0.0.0:8080
        - -etcd-endpoint
        - http://127.0.0.1:2379
