version: '3'

includes:
  runtime: ./runtime/Taskfile.yml

tasks:
  build:
    silent: true
    cmds:
      - go test -run '^$' ./cri
      - task: runtime:build

  test:
    silent: true
    cmds:
      - go test ./cri
      - task: runtime:test

  check:
    silent: true
    cmds:
      - "command -v go >/dev/null 2>&1 && echo '[cri] Go ok' || { echo '[cri] Go failed'; exit 1; }"
      - task: runtime:check
