version: '3'

tasks:
  build:
    silent: true
    cmds:
      - go test -run '^$' ./cri

  test:
    silent: true
    cmds:
      - go test ./cri

  check:
    silent: true
    cmds:
      - task: check:tools
      - task: check:user-namespace
      - task: check:pid-mount-namespace

  check:tools:
    silent: true
    cmds:
      - "command -v cc >/dev/null 2>&1 && echo '[cri] C compiler ok' || { echo '[cri] C compiler failed'; exit 1; }"
      - "command -v unshare >/dev/null 2>&1 && echo '[cri] unshare ok' || { echo '[cri] unshare failed'; exit 1; }"
      - "command -v mount >/dev/null 2>&1 && echo '[cri] mount ok' || { echo '[cri] mount failed'; exit 1; }"

  check:user-namespace:
    silent: true
    cmds:
      - "unshare --user --map-root-user --fork true >/dev/null 2>&1 && echo '[cri] user namespace ok' || { echo '[cri] user namespace failed'; exit 1; }"

  check:pid-mount-namespace:
    silent: true
    cmds:
      - "unshare --user --map-root-user --pid --mount --fork true >/dev/null 2>&1 && echo '[cri] PID/mount namespace ok' || { echo '[cri] PID/mount namespace failed'; exit 1; }"
